### ISSUE TITLE
Build system is broken

### ISSUE THREAD

**Issue by ZedThree** [pniedzielski/doxymacs#10]
`automake` complains that NEWS, AUTHOR and ChangeLog are missing. `prepare_release.sh` creates NEWS.md and AUTHOR.md, which could be trivially renamed. Alternatively, `--foreign` can be passed to `automake` in `bootstrap` which just ignores these files (see [here](https://github.com/ZedThree/doxymacs/commit/c79a3e82ca4aa21f6bb65206bf16a797ad6685f8)).

**Comment by pniedzielski** [comment]
Addressed by PR #13 .

**Comment by pniedzielski** [comment]
Fixed with e9d3bad.
